:bug: Fix PUT settings not updating the value. (#257)
Fix BaseHandler.fields() not including json fields []byte.
Fixes PUT on:
- tasks, taskgroups
- applications (facts & repository)
- applications/facts
- settings

Fixes docker build. The reflect.Ptr was renamed to reflect.Pointer in
1.18. The dockerfile includes
[go-toolset:latest](https://catalog.redhat.com/software/containers/ubi9/go-toolset/5ce8713aac3db925c03774d1?container-tabs=overview)
which includes 1.18.9. The patch to use (deprecated) reflect.Ptr should
not be necessary. But, the docker build fails without it.

```
# github.com/konveyor/tackle2-hub/api
api/base.go:143:9: undefined: reflect.Pointer
make: *** [Makefile:30: vet] Error 2

```

Regression introduced in pull/255
[here](https://github.com/konveyor/tackle2-hub/pull/255/files#diff-b3ac3832e61047a1ffffe16d97019d06999f7c9653bc29f35212efbe18f88210R155).

Signed-off-by: Jeff Ortel <jortel@redhat.com>